application: tgt-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /templates
  static_dir: templates

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest